src/App.js, src/components/home/Home.js, src/components/login/Login.js, src/components/login/login.css, src/components/navigation/Navigation.js, src/components/tasks/Tasks.js, src/constants/Constants.js, src/index.js, src/store/actions/authActions.js, src/store/reducers/authReducer.js
-We're now able to handle authentication in a much simpler way, thanks to redux
-Also added logic to only allow Tala emails to access gezako, and a set of test emails(non tala emails)
-Added a company collection so that all Tala data is stored under the Tala document in firestore
=> Update login logic using redux

src/components/login/login.css, src/fbConfig.js
Use staging for testing by default
=> Use staging env

src/App.js, src/components/perfomance/PerformanceTests.js, src/components/tasks/CreateTask.js, src/components/tasks/TaskDetails.js, src/components/tasks/Tasks.js, src/components/testreports/ReportDetails.js, src/components/testreports/UploadReport.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js, src/store/actions/reportActions.js
Add coming soon Performance test page
Fix tasks getting posted to wrong collections
Authenticate all unauthenticated pages
=> Attempt to remove hardcoded report and add new pages

src/App.js, src/components/sidepanel/Links.js, src/components/sidepanel/Sidepanel.js, src/components/sidepanel/sidepanel.css, src/components/testreports/UploadReport.js, src/components/testreports/completedspocktests/CompletedReportDetails.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/spocktestsindevelopment/DevelopmentReportDetails.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js
We now have CompleteReportDetails and DevelopmentReportDetails as a temporary fix
=> Split up report details into different classes

src/components/testreports/completedspocktests/CompletedReportDetails.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/spocktestsindevelopment/DevelopmentReportDetails.js, src/store/actions/reportActions.js
=> Remove hardcoded reports

src/App.js, src/components/testreports/UpdateReport.js, src/components/testreports/completedspocktests/CompletedReportDetails.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/report.css, src/components/testreports/spocktestsindevelopment/DevelopmentReportDetails.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js, src/store/actions/reportActions.js, src/store/reducers/reportReducer.js
Also displaying only first name on reports list
=> Add functionality to update report

README.md, src/components/testreports/UpdateReport.js, src/components/testreports/UploadReport.js, src/components/testreports/completedspocktests/CompletedReportDetails.js, src/components/testreports/report.css
=> post release updates

src/App.js, src/components/login/Login.js, src/components/testreports/UploadReport.js, src/components/testreports/completedspocktests/CompletedReportDetails.js, src/components/testreports/spocktestsindevelopment/DevelopmentReportDetails.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js, src/store/actions/authActions.js, src/store/reducers/authReducer.js
Store user's prevUrl so they can be redirected to the same url once they log in
=> Store user's prevUrl

src/components/testreports/UploadReport.js
add back missing upload button
=> add back missing upload button

src/App.js, src/components/sidepanel/Links.js, src/components/testreports/reportdetails/ReportDetails.js, src/components/testreports/updatereport/UpdateReport.js, src/components/testreports/uploadreport/UploadReport.js, src/store/actions/reportActions.js
=> Add ability to edit and delete report

src/components/status/StatusCard.js, src/components/testreports/Report.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js, src/components/testreports/uploadreport/UploadReport.js, src/store/actions/authActions.js, src/store/actions/reportActions.js, src/store/reducers/authReducer.js, src/util/StringUtil.js
Show assignee in reports detailed view and in report status card
=> Add assignee to report

.firebaserc, README.md, functions/index.js, src/components/snackbar/CustomSnackbar.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/completedspocktests/completedspockreports.css, src/components/testreports/completedspocktests/coverage/CoverageDialog.js, src/components/testreports/createreport/CreateReport.js, src/constants/FireStore.js, src/fbConfig.js, src/index.js, src/store/actions/authActions.js, src/store/actions/reportActions.js, src/store/reducers/reportReducer.js, src/store/reducers/snackbarReducer.js
Set up functions
Add dialog for updating coverage
=> Add coverage to spock tests home page

src/App.js, src/components/error/ErrorBoundary.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/completedspocktests/completedspockreports.css, src/components/testreports/createreport/CreateReport.js, src/components/testreports/reportdetails/ReportDetails.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js, src/components/testreports/updatereport/UpdateReport.js, src/constants/Report.js, src/store/actions/reportActions.js, src/store/reducers/reportReducer.js, src/util/StringUtil.js
Also converted UpdateReport class into a function component
=> Add product and design spec links

README.md, functions/index.js, package.json, src/components/error/ErrorBoundary.js, src/components/login/Login.js, src/components/noreports/NoReportsScreen.js, src/components/noreports/noreports.css, src/components/status/StatusCard.js, src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/createreport/CreateReport.js, src/components/testreports/reportdetails/ReportDetails.js, src/components/testreports/spocktestsindevelopment/SpockTestsInDevelopment.js, src/components/testreports/updatereport/UpdateReport.js, src/constants/Report.js, src/fbConfig.js, src/store/actions/reportActions.js, src/store/reducers/reportReducer.js, src/util/StringUtil.js
Add no reports available text if no reports are available
=> Post deploy fixes

src/components/sidepanel/SideBar.js, src/components/testreports/createreport/CreateReport.js, src/components/testreports/updatereport/UpdateReport.js
=> Add lending partner

src/components/testreports/createreport/CreateReport.js, src/components/testreports/updatereport/UpdateReport.js
=> fix report update bug

src/App.js, src/components/testreports/createreport/CreateReport.js, src/components/testreports/report.css, src/components/testreports/reportdetails/ReportDetails.js, src/components/testreports/reportdetails/reportdetails.css, src/components/testreports/reportdetails/spockreportcustomstyles.css, src/components/testreports/updatereport/UpdateReport.js, src/store/actions/reportActions.js
- Also add proper error text when no product spec or tech design spec is set
- Remove some unused css
=> Add postman tests link to report details

src/components/testreports/completedspocktests/CompletedSpockTests.js, src/components/testreports/createreport/CreateReport.js, src/components/testreports/reportdetails/ReportDetails.js, src/components/testreports/reportdetails/reportdetails.css, src/components/testreports/updatereport/UpdateReport.js, src/store/actions/reportActions.js
=> Add Github PR link to report details

src/components/testreports/createreport/CreateReport.js, src/components/testreports/updatereport/UpdateReport.js, src/store/actions/authActions.js, src/store/reducers/authReducer.js
Create Report page was constantly calling Firestore hence maxing out our free 50k reads Quota
=> Fix createReport bug to stop maxing out the free 50k read daily quota

package.json, src/components/comments/Comment.js, src/components/comments/CreateOrEditComment.js, src/components/comments/comments.css, src/components/navbar/NavBar.js, src/components/sidepanel/Links.js, src/components/sidepanel/SideBar.js, src/components/sidepanel/sidepanel.css, src/components/tests/features/featuredetails/FeatureDetails.js, src/components/tests/features/viewfeatures/Features.js, src/components/tests/features/viewfeatures/features.css
- Comments Styling
- Design Optimisations
=> Trello v1.7 Design optimisations

README.md, src/components/features/featuresdbhandlers/CreateFeatureDbHandler.js, src/components/features/featuresdbhandlers/GetFeatureByIdDbHandler.js, src/constants/FireStore.js, src/index.js, src/store/actions/authActions.js, src/store/actions/featureActions.js, src/store/actions/reportActions.js, src/store/reducers/authReducer.js, src/util/StringUtil.js
Sets up mamaope emails so that mamaope users can login
Next: Need to be able to set company specific Apps/Service, because currenlty, mamaope users can see the hardcoded Tala service.
Jira: https://powem.atlassian.net/browse/GEZ-20
=> GEZ-20 Setup mamaope emails
